# Generated by Django 4.2.6 on 2023-11-26 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='answer',
            field=models.BooleanField(choices=[(True, 'True'), (False, 'False')]),
        ),
    ]
